/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HospitalMedLedger } from './HospitalMedLedger.js';
export * as factories from './factories/index.js';
export { HospitalMedLedger__factory } from './factories/HospitalMedLedger__factory.js';